### ISSUE TITLE
Explore machine learning models for object detection

### ISSUE THREAD

**Issue by raj2729** [UCI-SAP-Capstone-2024/Proof-of-Performance-Validation#11]
There are a ton of models available for object detection. Explore which models could be suitable for our needs:

1. Logo Detection - Brands and Products etc
2. Text Detection - Quantity and Brand Name etc
3. Promotion Detection - car promotion, vending machine promotion etc

These models are to be trained later to check for the best model that suits our objectives.

**Comment by robschu** [comment]
Output: List of models to be evaluated.

**Comment by deapdaru** [comment]
Reference:
https://docs.google.com/presentation/d/1SbqihKQY3Dg672rokSmJTXthrZq6lgwpiSyXJPFGf6w/edit?usp=sharing

**Comment by raj2729** [comment]
We have decided to move ahead with Detectron2 Object Detection Model which performed well and had a better accuracy than YOLO and Tensorflow Object Detection Models.
