### ISSUE TITLE
How can we narrow it down based on our data?

### ISSUE THREAD

**Issue by Nike1421** [UCI-SAP-Capstone-2024/Proof-of-Performance-Validation#6]

**Comment by robschu** [comment]
Look at dataset and existing properties to find out what can be used to map to labels or extracted text from the image extraction / model output. 

Output: List of promising property

**Comment by puneater** [comment]
We have finalized to use a Convolutional Neural Network (CNN) model for our problem which inherently extracts features from the data, in our case images. We would not require to build a separate feature extraction process for our solution.
