### ISSUE TITLE
Process flow exploration

### ISSUE THREAD

**Issue by puneater** [UCI-SAP-Capstone-2024/Proof-of-Performance-Validation#8]
The validation can be done in two ways,

1. After we detect all the necessary information from the proof images, we can trace what promotion does it belong to
2. Other way would be to first filter out all the active promotions in the retail store and then validate if all of them are present in the images.

We can explore these ways and can finalize once we have all the data and check the feasibility of each flow.

**Comment by Nike1421** [comment]
A rough overview of the process is shown in the figure below:

![Image](https://github.com/UCI-SAP-Capstone-2024/Proof-of-Performance-Validation/assets/67200520/8a3d353b-6bd3-4e95-9bb7-e453799b7129)

**Comment by puneater** [comment]
We are going to follow the process flow 1:
"After we detect all the necessary information from the proof images, we can trace what promotion does it belong to".
We will gather all the information from the proof using object detection and image's metadata to use it for filtering promotions to get to the correct one.
