### ISSUE TITLE
Identifying Brands

### ISSUE THREAD

**Issue by Nike1421** [UCI-SAP-Capstone-2024/Proof-of-Performance-Validation#9]
Many brands can have one parent company. e.g., The Coca-Cola company owns multiple brands like Sprite, Dasani, etc.  and we need to identify each brand and tie the promotions with the brand or company.

**Comment by robschu** [comment]
Output: List of brands and logos for a company on different hierarchy levels.

**Comment by Nike1421** [comment]
I have been surfing the company websites to list down all the brands that a particular company owns.

Till now, I have scraped data for three companies: Coca-Cola Company, Nestle and PepsiCo.

Link: https://ucirvine-my.sharepoint.com/:x:/r/personal/naiko_ad_uci_edu/Documents/Documents/Brands.xlsx?d=w7e8bcfb434f14562a3ebb5b12600c304&csf=1&web=1&e=y2EzBw

Issues I am facing:
- Companies do not list all brands and in some cases, data is not available publicly from first-party sources
- No specific product hierarchy
- Will need to find logos separately

What I need:
- A list of brands that we need to focus on

**Comment by Nike1421** [comment]
As per last week's discussion, I searched Google Images for images of promotions for products from the three companies mentioned in the previous comment as well as from Red Bull.

From these companies, I have marked the products from Coca-Cola Company, PepsiCo and Red Bull for which I could find images of retail promotions in supermarkets. I have also marked those products for which there are lots of promotional images. Products include beverages and chips.

In addition, I have compiled a detailed product hierarchy for most, if not all, Coca-Cola Beverage products.

To-do:
- I need to check possible promotional images for alcoholic beverages (e.g. Beer)
- Identification of products

Discussion Topic:
- Kit-Kat

**Comment by Nike1421** [comment]
After careful review of all the brands and their products, as well as the availability of brand promotion images, it has emerged that for the Validation Project, we will restrict ourselves to the following brands and products:

1. Coca-Cola Company
- Coca-Cola (and it's variants as a future scope)
- Monster Energy
- Sprite

2. Red Bull GmBh
- Red Bull

3. PepsiCo
- Pepsi
- Mountain Dew

4. Nestle
- KitKat

5. Duracell
-  Duracell Batteries
